[project]
name = "unit-converter"
version = "0.1.0"
description = "Unit converter to convert between different units of measurement."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.1",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]
